import {test,expect} from '@playwright/test';
for(const width of [1440,390])test(`personal building, expansion and hair persist ${width}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/?profile=build-a');await page.locator('#close-dialog').click();await page.locator('#open-map').click();await page.locator('[data-travel=village]').click();
 await page.evaluate(()=>{const key='dream-caravan:garden:v1:profile:build-a',s=JSON.parse(localStorage.getItem(key)!);s.essence=100;localStorage.setItem(key,JSON.stringify(s));});await page.reload();await page.locator('#close-dialog').click();await page.locator('#open-map').click();await page.locator('[data-travel=village]').click();
 await page.locator('#open-build').click();await expect(page.locator('.builder')).toContainText('قطر زمین 64');await page.locator('#expand-region').click();await expect(page.locator('.builder')).toContainText('قطر زمین 72');await expect(page.locator('[data-slot]')).toHaveCount(12);
 await page.locator('[data-furnishing=pavilion]').click();await page.locator('[data-slot="0"]').click();await expect(page.locator('[data-slot="0"]')).toContainText('کوشک');await page.locator('[data-slot="0"]').click();await page.locator('[data-slot="3"]').click();await expect(page.locator('[data-slot="3"]')).toContainText('کوشک');await expect(page.locator('[data-slot="0"]')).toContainText('خالی');
 await page.locator('[data-hair=brown]').click();await expect(page.locator('[data-hair=brown]')).toHaveAttribute('aria-pressed','true');await page.screenshot({path:`previews/expansion-builder-${width}.png`});await page.locator('[data-project=market]').click();await page.locator('#close-dialog').click();await page.waitForTimeout(1200);await page.screenshot({path:`previews/expansion-village-${width}.png`});
 await page.reload();await page.locator('#close-dialog').click();await page.locator('#open-map').click();await page.locator('[data-travel=village]').click();await page.locator('#open-build').click();await expect(page.locator('[data-slot="3"]')).toContainText('کوشک');await expect(page.locator('[data-hair=brown]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('.builder')).toContainText('گسترش 1/۲۰');
 await page.locator('[data-slot="3"]').click();await page.locator('#remove-decoration').click();await expect(page.locator('[data-slot="3"]')).toContainText('خالی');
 await page.goto('/?profile=build-b');await page.locator('#close-dialog').click();await page.locator('#open-build').click();await expect(page.locator('[data-hair=white]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('[data-slot]')).toHaveCount(8);await expect(page.locator('.builder')).toContainText('0 سازه');expect(errors).toEqual([]);
});
