import * as T from 'three';
import {test,expect} from '@playwright/test';
for(const width of [1440,390])test(`region isolation, planting and flight ${width}`,async({page})=>{
 test.setTimeout(120000);await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?profile=region-test');await page.locator('#close-dialog').click();
 await page.waitForTimeout(2000);const cam=new T.PerspectiveCamera(40,width/900,.1,100);cam.position.copy(new T.Vector3(2,0,7)).add(width<700?new T.Vector3(15,21,24):new T.Vector3(14,19,23));cam.lookAt(2,0,7);cam.updateMatrixWorld();const point=new T.Vector3(-1.5,.16,9.5).project(cam);await page.locator('#world canvas').click({position:{x:(point.x+1)*width/2,y:(1-point.y)*900/2}});await expect(page.locator('.garden-panel')).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('dream-caravan:garden:v1:profile:region-test')!).plants.length)).toBe(1);await page.locator('#garden-close').click();
 await page.locator('#open-garden').click();await expect(page.locator('.garden-panel')).toBeVisible();if(!await page.locator('details').getAttribute('open')){if(!await page.locator('details').evaluate(e=>e.hasAttribute('open')))await page.locator('summary').click();}await page.locator('#cell-2-2').click();await expect(page.locator('.plant-info')).toContainText('بذر');await page.locator('#garden-move').click();await page.locator('#cell-3-3').click();await page.locator('#garden-close').click();
 await page.locator('#flight-toggle').click();await expect(page.locator('#flight-toggle')).toHaveAttribute('aria-pressed','true');await expect.poll(async()=>Number(await page.locator('#flight-toggle').getAttribute('data-altitude'))).toBeGreaterThan(1);await page.screenshot({path:`previews/regions-flight-${width}.png`});
 await page.locator('#open-map').click();await page.locator('[data-travel=village]').click();await expect(page.locator('main')).toHaveAttribute('data-region','village');await expect(page.locator('[data-marker=seed]')).toBeHidden();await expect(page.locator('[data-marker=heart]')).toBeHidden();await page.screenshot({path:`previews/regions-village-${width}.png`});
 await page.locator('#flight-toggle').click();await expect.poll(async()=>Number(await page.locator('#flight-toggle').getAttribute('data-altitude'))).toBeLessThan(.1);await page.locator('#open-garden').click();await expect(page.locator('main')).toHaveAttribute('data-region','garden');if(!await page.locator('details').getAttribute('open')){if(!await page.locator('details').evaluate(e=>e.hasAttribute('open')))await page.locator('summary').click();}await page.locator('#cell-3-3').click();await expect(page.locator('.plant-info')).toContainText('گل ماه');await page.screenshot({path:`previews/regions-garden-${width}.png`});expect(errors).toEqual([]);
});
