import { test, expect } from '@playwright/test';
for(const width of [1440,390]) test(`all districts, spending, hybrid and saved world ${width}`,async({page})=>{
 test.setTimeout(240000);await page.clock.install();await page.setViewportSize({width,height:900});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 // Mature plants are seeded to test building progression without a real ten-minute wait.
 await page.addInitScript(()=>{if(!localStorage.getItem('dream-caravan:garden:v1:profile:world-test'))localStorage.setItem('dream-caravan:garden:v1:profile:world-test',JSON.stringify({version:1,collected:[],invention:null,restored:false,plotLevel:3,plants:[{id:'moon',species:'moonflower',col:2,row:2,plantedAt:0,boostMs:0,lastWaterAt:0},{id:'sun',species:'sunblossom',col:3,row:2,plantedAt:0,boostMs:0,lastWaterAt:0}],essence:100,houseLevel:0,projects:[],hybrids:false,aura:0,visited:['garden']}));});
 await page.goto('/?profile=world-test');await page.locator('#close-dialog').click();
 async function travel(id:string){await page.locator('#open-map').click();await expect(page.locator('[data-travel]')).toHaveCount(6);await page.locator(`[data-travel="${id}"]`).click();}
 await travel('grove');await expect(page.locator('#district-name')).toHaveText('بیشهٔ روح');await page.locator('#district-action').click();await page.locator('#gather-light').click();await expect(page.locator('#gather-light')).toBeDisabled();await page.locator('[data-project="bridge"]').click();await expect(page.locator('[data-project="bridge"]')).toBeDisabled();await page.locator('#close-dialog').click();
 await travel('home');await page.locator('#district-action').click();for(let i=0;i<3;i++)await page.locator('#upgrade-house').click();await expect(page.locator('#upgrade-house')).toBeDisabled();await page.locator('#close-dialog').click();await page.screenshot({path:`previews/world-home-${width}.png`});
 await travel('village');await page.locator('#district-action').click();await page.locator('[data-project="lamps"]').click();await page.locator('[data-project="fountain"]').click();await expect(page.locator('[data-project="lamps"]')).toBeDisabled();await page.locator('#close-dialog').click();await page.screenshot({path:`previews/world-village-${width}.png`});
 await travel('greenhouse');await page.locator('#district-action').click();await page.locator('[data-project="greenhouse"]').click();await page.locator('#hybrid-discovery').click();await expect(page.locator('#hybrid-discovery')).toHaveText('سوسن ستاره کشف شد');await page.locator('#close-dialog').click();
 await travel('sanctuary');await page.locator('#district-action').click();for(let i=0;i<3;i++)await page.locator('#awaken-aura').click();await expect(page.locator('#awaken-aura')).toBeDisabled();await page.locator('#close-dialog').click();await page.screenshot({path:`previews/world-sanctuary-${width}.png`});
 await travel('garden');await page.locator('#species-starlily').click();await page.locator('summary').click();await page.locator('#cell-4-4').click();await expect(page.locator('.plant-info')).toContainText('سوسن ستاره');
 await page.locator('#cell-2-2').click();await page.locator('#garden-harvest').click();await expect(page.locator('#garden-harvest')).toBeDisabled();
 await page.locator('#garden-design').click();await page.locator('[data-project="bench"]').click();await page.locator('[data-project="pond"]').click();await page.locator('#close-dialog').click();
 const before=await page.evaluate(()=>localStorage.getItem('dream-caravan:garden:v1:profile:world-test'));const s=JSON.parse(before!);expect(s).toMatchObject({essence:11,houseLevel:3,hybrids:true,aura:3});expect(s.visited).toHaveLength(6);expect(s.projects).toHaveLength(6);
 await page.reload();await page.locator('#close-dialog').click();expect(await page.evaluate(()=>localStorage.getItem('dream-caravan:garden:v1:profile:world-test'))).toBe(before);
 await page.locator('#open-map').click();await page.screenshot({path:`previews/world-map-${width}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('fully grown 12x12 garden retains all plants on mobile',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:900});
 await page.addInitScript(()=>localStorage.setItem('dream-caravan:garden:v1:profile:large',JSON.stringify({version:1,collected:[],plotLevel:5,plants:Array.from({length:144},(_,i)=>({id:`plant-${i}`,species:['moonflower','sunblossom','spiritfern'][i%3],col:i%12-2,row:Math.floor(i/12)-2,plantedAt:0,boostMs:0,lastWaterAt:0})),visited:['garden']})));
 await page.goto('/?profile=large');await page.locator('#close-dialog').click();await page.locator('#open-garden').click();await expect(page.locator('.garden-heading')).toContainText('12×12');await expect(page.locator('#garden-expand')).toBeDisabled();await page.locator('summary').click();await expect(page.locator('[data-col]')).toHaveCount(144);await page.locator('#cell--2--2').click();await expect(page.locator('.plant-info')).toContainText('شکوفه');await page.locator('#garden-move').click();await page.locator('#cell--1--2').click();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('dream-caravan:garden:v1:profile:large')!).plants.length)).toBe(144);expect(errors).toEqual([]);await page.screenshot({path:'previews/world-full-garden-mobile.png'});
});
